name: LADAWARDS
favicon: null
layout_spectrum: 1
typography_spectrum: 0.14123779814690351
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#594546'
    - '#b0b5bd'
    - '#7ef47b'
    - '#ea446c'
  brandStrength: 0.3125
  lightness: 0.834875215543434
  saturation: 0.6875
  rhythmicContrast: 0.8335075355134904
purpose: []
